### ISSUE TITLE
Queue Pop Stack Trace

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/snmp#4]
The following is being tossed out to stderr:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/project/blocks/snmp/snmp_block.py", line 62, in _request_GET
    lookupValues=self.lookup_values)
  File "/home/ubuntu/nio_versions/1.4.1/lib/python3.4/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 426, in getCmd
    self.__asynCmdGen.snmpEngine.transportDispatcher.runDispatcher()
  File "/home/ubuntu/nio_versions/1.4.1/lib/python3.4/site-packages/pysnmp/carrier/asynsock/dispatch.py", line 41, in runDispatcher
    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
;  File "/home/ubuntu/nio_versions/1.4.1/lib/python3.4/site-packages/pysnmp/carrier/asynsock/dispatch.py", line 37, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/usr/lib/python3.4/asyncore.py", line 212, in loop
    poll_fun(timeout, map)
;  File "/usr/lib/python3.4/asyncore.py", line 193, in poll2
    readwrite(obj, flags)
;  File "/usr/lib/python3.4/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/usr/lib/python3.4/asyncore.py", line 110, in readwrite
    obj.handle_write_event()
;  File "/usr/lib/python3.4/asyncore.py", line 461, in handle_write_event
    self.handle_write()
;  File "/home/ubuntu/nio_versions/1.4.1/lib/python3.4/site-packages/pysnmp/carrier/asynsock/dgram/base.py", line 60, in handle_write
    outgoingMessage, transportAddress = self.__outQueue.pop(0)
;IndexError: pop from empty list
```

**Comment by mattdodge** [comment]
@adiazg you may want to take a look at this

**Comment by mattdodge** [comment]
This was also in the nio logs, seemingly at the same time the stack trace occurred.

```
SNMP GET Error: No SNMP response received before timeout
```

**Comment by mattdodge** [comment]
Just upgraded the SNMP block on the brand instance to the new, signal driven block. Will check back to see if there are any SNMP errors in nio.err after this. It's possible latest overhaul took care of this

**Comment by mattdodge** [comment]
7 days and no logs to stderr. There have also been no errors reported to the service logs so it's possible whatever was causing this just hasn't happened again. But I'm going to close this for now and reopen if it happens again
